#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org

START=99
start() {
        sleep 2   # make sure boot process is done, no more console msgs
        echo "Radio Started"
        . /etc/profile
        echo $PATH
        sh /root/interface.sh &
}
